
import React from "react";
import SocialButtons from "../../authforms/SocialButtons";
import AuthLogin from "../../authforms/AuthLogin";
import LeftSidebarPart from "../LeftSidebarPart";
import rightBgimg from "/public/images/backgrounds/leaf-right.png"
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Side Login Authentication",
  description: "Generated by create next app",
};
import Link from "next/link";
import FullLogo from "@/app/(DashboardLayout)/layout/shared/logo/FullLogo";
import Image from "next/image";
import AuthRegister from "../../authforms/AuthRegister";
const Register = () => {
  return (
    <>
      <div className="relative overflow-hidden h-screen after:absolute 2xl:after:bg-contain after:bg-cover after:top-0 after:start-0 after:bg-no-repeat after:w-full after:h-full after:bg-[url('/images/backgrounds/login-bg.png')]">
        <div className="grid grid-cols-12 gap-3 h-screen dark:bg-darkgray relative z-[999] bg-transparent">
          <div className="xl:col-span-8 lg:col-span-7 col-span-12 md:block hidden relative overflow-hidden">
            <LeftSidebarPart />        
          </div>
          <div className="xl:col-span-4 lg:col-span-5 col-span-12 sm:px-12 px-4 relative z-10 lg:bg-white bg-transparent">
          <div className="flex h-screen items-center px-3 justify-center ">
              <div className="max-w-[460px] w-full bg-white rounded-md  p-4 md:mt-0 mt-20">
                <h3 className="text-2xl font-bold my-3 mb-1">Welcome to Adminpro</h3>
                <p className="text-darklink text-sm font-medium">
                  Your Admin Dashboard
                </p>
                <SocialButtons title="or sign up with" />
                <AuthRegister />
                <div className="flex gap-2 text-base text-dark dark:text-white font-medium mt-6 items-center justify-start">
                  <p>Already have an Account?</p>
                  <Link
                    href={"/auth/auth1/login"}
                    className="text-primary text-sm font-medium"
                  >
                    Sign in
                  </Link>
                </div>
              </div>
            </div>
            <div className="absolute end-0 bottom-0 z-1 md:block hidden">
            <Image src={rightBgimg} alt="img"/>
             </div>
             <div className="fixed top-0 start-0 ps-4" ><FullLogo/></div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Register;
